### ISSUE TITLE
Use cases

### ISSUE THREAD

**Issue by justinfagnani** [webcomponents/custom-elements-json#1]
I listed some initial use cases in the [README](https://github.com/webcomponents/custom-elements-json/blob/master/README.md). If there are additional use cases that should be added, propose them here.

**Comment by Westbrook** [comment]
As discussed in https://github.com/open-wc/catalog/issues/8#issue-503622493 the presence of a `custom-elements.json` can also be used as a flag to outline that a package exports an actual custom element. In the past `keyword` entries in a `package.json` have been useful for this sort of thing, common words like `component`, `custom element`, `web component`, etc. have been adopted more broadly across the community to mean less specific things. Having a standardized definition file with this explicit meaning (or from which this meaning can be reliably extracted) will go a long way towards simplifying the act of bringing the available masses of custom elements together in cataloging efforts both large (open-wc.org/webcomponents.org) and small (team/project/company catalogs).

**Comment by castastrophe** [comment]
A web component schema can also be used by a CMS in order to interpret the component and prompt the content users for input.

**Comment by thepassle** [comment]
Another use case that ive been hacking on this weekend is this chrome extension:

![demo](https://media.giphy.com/media/QAmgpisTDfXKY091Yh/giphy.gif)

It:
- Finds all custom elements on a page
- Selects all, or targets specific instances of an element
- Allows you to search the catalog for more information like the readme (docs!), github stars, npm link, etc etc

It could even be extended to implement 'knobs' á la Storybook so you can tweak properties etc right in your browser/the extension. This is only possible because of `custom-elements.json` 🙂 

(Disclaimer: I had to fork `time-elements` and add a `custom-elements.json` because github doesnt have it yet, but otherwise nothing is mocked or 'faked')

**Comment by btopro** [comment]
HAXSchema is how the HAX editor is able to communicate with web components and understands how to build our headless form fields to interface with them (See: [HAXschema](https://haxtheweb.org/hax-schema) and [example from video-player](https://github.com/elmsln/lrnwebcomponents/blob/master/elements/video-player/video-player.js#L158-L373) ). This schema is a lightweight abstraction of JSON Schema in order to provide support for human readable names and allow HAX to generate a headless form for adding and modifying web components in hax rendered areas of the page:

![Animation showing video-player being used in HAX via haxSchema method](https://user-images.githubusercontent.com/329735/68606298-261b4a80-047c-11ea-8a21-f9b2d8d35b41.gif)


Attributes / Properties, license, tag name and slot information could all help in automatically generating a large portion of the HAXschema wiring for a new element or we could even have a mode that would automatically generate the input forms off of this data.

**Comment by nuxodin** [comment]
A CE-json would be awesome!

The use case, which I would be very happy about, is the following:
I would be able to define custom elements whose script would be loaded automatically.
Especially useful for development.

Pseudocode:
```js
unregistred_CE_found( async el => {
    var schema = await search_CE_Registry( el.tagName || el.getAttribute('is') )
    import(schema.script);

    if (window.not_in_production) {
        instruct_the_server_to_implement_the_script( schema )
    }

})
```

**Comment by justinfagnani** [comment]
I'm going to close this and let new use cases be added via standalone issues or PRs. Thanks!
